# Listen to Your Heart {#Heart-Rhythm}

#### Keywords

heart-rate, heart disease, machine learning, cardiovascular, exercise, wearable devices

## Why listen to your heart?

According to the CDC, the leading cause of death for an American is heart disease [1]. I lost a friend recently to heart disease. I cannot testify to my friend’s cardiovascular fitness before his untimely passing but level of fitness is a predictor for cardiovascular mortality [2]. Understanding patterns in heart rhythms can optimize exercise performance and provide disease detection.

## How do I listen to my heart?

Heart-rate data can be collected using wearable devices such as smart watches, armband heart-rate monitors, and chest strap heart-rate monitors. Heart-rate patterns are an indicator of a variety of medical and non-medical conditions. For example, the pattern of a deconditioned heart during exercise appears distinct to the pattern illustrated by a heart that is trained by routine exercise. A deeper look at the changes of heart-rate during exercise can gives us clues to inform, for instance, whether shortness of breath from intense training is a sign of a deconditioned heart or an early indicator of heart disease.

## Service for the heart

We will build a software service and app to apply statistical analysis and machine learning to heart-rate data. We will develop insights and predictive capability to improve health and cardiovascular fitness. Users will initiate exercise heart-rate tracking using our smart watch app or smart phone app paired with a bluetooth heart-rate monitor. Based on age, weight, and exercise history, the app will provide the user with visual, aural, and haptic feedback to encourage the user to adjust level of workout intensity. For example, if a user shows signs of overexertion, the app will prompt the user to reduce the pace. Similarly, if a user is underperforming relative to previously tracked data, the user will be encouraged to increase exercise intensity. A user will be able to target heart rate zones to achieve specific health goals such as weight loss, muscle build, or cardiovascular conditioning. After an exercise session, a summary report will be provided to the user. We will provide the user with the opportunity to share summary data with health care providers. We expect analysis of population heart-rate data will give insight into the cardiovascular fitness of those ranging from the daily walker to the weekend warrior. We will encourage users to share anonymized data that we will aggregate for population study and sharing with researchers. 

## References

[1] https://www.cdc.gov/nchs/fastats/leading-causes-of-death.htm

[2] Sachin Gupta, Anand Rohatgi, Colby R. Ayers, Benjamin L. Willis, William L. Haskell, Amit Khera, Mark H. Drazner, James A. de Lemos and Jarett D. Berry. Cardiorespiratory Fitness and Classification of Risk of Cardiovascular Disease Mortality. Circulation. 2011;123:1377-1383, originally published March 31, 2011. https://doi.org/10.1161/CIRCULATIONAHA.110.003236
