# Wargames Database {#WargamesAPI}

#### Keywords

wargame, simulation, api, natural language processing, machine learning

## The Art of Wargames

Simulation is a medium for modeling systems or processes independent of real world environments. Wargame simulation is a commonly applied tool for development of military tactic, system design, and analysis. Military research laboratories and private contractors conduct computer-based wargame simulation exercises on large scale. Multiple times a year, dozens of simulation applications on hundreds of computers are networked linked between several geographically located analytic centers to test system performance and battle tactics long before metal is bent and rivets drilled on new weapon systems. In virtual wargame exercises, hundreds of people sit at computing terminals controlling geographically distributed entities as varied as an individual soldier to battalions composed of troops and tools of war such as tanks and fighter jets. The insights learned from testing ideas in virtual environments are the reward of wargame simulation. Behind the scenes, the risk associated with lead time required to collect the large amounts of data that drive the simulation presents opportunities for improvement.

## Behind the Curtain

The lead up to these massive wargame exercises, often referred to as scenario build, is its own symphony of complex research and information gathering. During scenario build, a common “ground truth” data set is compiled of, among other things, operating characteristics of the hundreds of thousands of digital entities that are to be employed in the exercise. Operating characteristics include, for example, attributes such as the top speed of a B-2 Stealth Bomber or the number of rounds available on the main gun of an M1 Abrams tank. Scenario build often takes on the order of weeks to months to complete. A hidden truth of scenario build is that analysts often “fat finger” operating characteristics into text documents that are cribbed from Jane’s Aerospace, Defense and Security manuals or, more likely, Wikipedia. These text documents are specifically formatted to be read into various simulation applications. 

Operating characteristics are only a slice of a bigger pie when it comes to the input data for a wargame exercise. Highly classified data such as radar signatures for top secret warplanes adds additional challenge to the scenario build process. Not only does an analyst have to have an appreciation of complex physics of radio waves but she must also have clearance and training for handling restricted information. Operating characteristics, on the other hand, are generally publically available high-level specification data that is easily gleaned from marketing material but crucial to modeling, for instance, the size of an object in 3-dimensional space. Why not simplify collection of publically accessible data to free analyst time to focus on the more complex data? Machine learning and natural language processing have lowered the barriers to mining structured and unstructured text data for the nuggets of information that are most useful.

## A Better Way

We aim to build an algorithm to scrap and parse Wikipedia for operating characteristics of military systems to generate a massive database that represents the hierarchical structure of all the world’s fighting forces. We will make the database publically available on the internet via an Application Programming Interface (API). Suppose, for instance, that an analyst seeks to build a scenario that models the sequence of events that are a likely response to North Korea launching a missile towards a U.S. base in Guam. The notional operational range for a variety of anti-ballistic missiles is provided in the specification section of Wikipedia pages with search and deep reading. Alternatively, the specifications could be easily imported directly into simulation and visualized on a map with rings that represent range using an API connection. Or perhaps, if a university instructor seeks to develop a map-based narrative recreating the reconnaissance missions flown by U.S. airmen during the Cuban Missile Crisis. The cruise speed and maximum altitude for a U-2 spy plane can be read directly into the modeling or visualization environment that will represent the historical context. Users could link to the API to extract data relevant to any historical or hypothetical military scenario shifting the analytical focus from management of technical details to illustration of important storylines and testing of mission critical concepts.
